#!/usr/bin/env python3
"""Pre-charge en RAM les fichiers des torrents les plus actifs."""
import json
import urllib.request
import urllib.parse
import subprocess
import os

QB_URL  = 'http://127.0.0.1:8181'
QB_USER = 'ropixv2'
QB_PASS = 'Lip8NebW8Z8HrbX'
MAX_WARM_GB = 30  # ne pas cacher plus de 30 GB
cookie = None

def qb_request(endpoint, data=None):
    global cookie
    url = f'{QB_URL}{endpoint}'
    if data:
        data = urllib.parse.urlencode(data).encode()
    req = urllib.request.Request(url, data=data)
    if cookie:
        req.add_header('Cookie', cookie)
    resp = urllib.request.urlopen(req, timeout=10)
    sc = resp.headers.get('Set-Cookie')
    if sc:
        cookie = sc.split(';')[0]
    return resp.read().decode()

qb_request('/api/v2/auth/login', {'username': QB_USER, 'password': QB_PASS})
torrents = json.loads(qb_request('/api/v2/torrents/info?filter=active'))

# Trier par nombre de leechers (plus demandes en premier)
torrents.sort(key=lambda t: -t.get('num_incomplete', 0))

warmed = 0
for t in torrents:
    if warmed >= MAX_WARM_GB * 1024**3:
        break
    h = t['hash']
    size = t.get('total_size', 0)
    if size > 10 * 1024**3:  # skip fichiers > 10 GB
        continue
    # Get file list
    files = json.loads(qb_request(f'/api/v2/torrents/files?hash={h}'))
    for f in files:
        fpath = os.path.join(t['save_path'], f['name'])
        if os.path.exists(fpath) and f.get('size', 0) < 10 * 1024**3:
            # Read file to pull into page cache
            try:
                with open(fpath, 'rb') as fh:
                    while fh.read(4 * 1024 * 1024):  # 4MB chunks
                        pass
                warmed += f.get('size', 0)
            except Exception:
                pass

print(f'Warmed {warmed/1024**3:.1f} GB into page cache')
